version: 2
jobs:
  build:
    working_directory: ~/docker-elasticsearch
    docker:
      - image: docker:17.07.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          reusable: true
          exclusive: true
      - run:
          name: Install bash
          command: |
            apk add --no-cache bash curl

      - run:
          name: Build
          command: |
            docker build -t veltra/elasticsearch .

      - run:
          name: Run tests
          command: |
            docker run \
              -E"ES_JAVA_OPTS=-Xmx256m -Xms256m" \
              -E"xpack.security.enabled=true" \
              -E"xpack.monitoring.enabled=false" \
              -E"xpack.watcher.enabled=false" \
              -E"xpack.graph.enabled=false" \
              --name elasticsearch veltra/elasticsearch; sleep 15
            docker run --network container:elasticsearch appropriate/curl --retry 10 --retry-connrefused -u elastic:changeme http://localhost:9200
