version: 2
jobs:
  build:
    working_directory: ~/docker-elasticsearch
    docker:
      - image: docker:17.07.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          reusable: true
          exclusive: true
      - run:
          name: Install bash
          command: |
            apk add --no-cache bash curl

      - run:
          name: Build
          command: |
            docker build -t my-app .

      - run:
          name: Run tests
          command: |
            docker run -d -p 9200:9200 --name my-app my-app; sleep 15
            docker run --network container:my-app appropriate/curl --retry 10 --retry-connrefused -u elastic:changeme http://localhost:9200
